### ISSUE TITLE
Connecting to localhost fails.

### ISSUE THREAD

**Issue by rhysd** [invisibleroads/socketIO-client#41] opened 2014-01-22 11:41 UTC
Hi.

I have a trouble with connecting local server with socketIO-client.
socket.io server was running on node.js at localhost:3000 and I tried below python code as a client side to communicate with server by socket.io.

```python
from socketIO_client import SocketIO
import logging

logging.basicConfig(level=logging.DEBUG)

def on_message_response(*args):
    print 'on_message_response', args

with SocketIO(
    'localhost',
    3000,
    proxies={'http': 'http://xxxxx.xxx.xxxx.co.jp:10080'}
) as socketIO:
    socketIO.emit('message', {'value': 'Hey, from python'}, on_message_response)
    socketIO.wait_for_callbacks(seconds=1)
```

On connecting to server,  below error occured.  Is this a bug of socketIO-client? Or I've made some mistakes?

- Ubuntu 12.04
- python 2.7.5
- socketIO-client 0.5.3

Thanks.

```
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): xxxxx.xxx.xxxx.co.jp
DEBUG:requests.packages.urllib3.connectionpool:"GET http://localhost:3000/socket.io/1/ HTTP/1.1" 301 None
Traceback (most recent call last):
  File "socket_io_client_test.py", line 11, in <module>
    3000,
  File "/home/hayashida/.pyenv/versions/2.7.5/lib/python2.7/site-packages/socketIO_client/__init__.py", line 136, in __init__
    self.define(Namespace)
  File "/home/hayashida/.pyenv/versions/2.7.5/lib/python2.7/site-packages/socketIO_client/__init__.py", line 150, in define
    namespace = Namespace(self._transport, path)
  File "/home/hayashida/.pyenv/versions/2.7.5/lib/python2.7/site-packages/socketIO_client/__init__.py", line 237, in _transport
    self.__transport = self._get_transport()
  File "/home/hayashida/.pyenv/versions/2.7.5/lib/python2.7/site-packages/socketIO_client/__init__.py", line 251, in _get_transport
    self.is_secure, self.base_url, **self.kw)
  File "/home/hayashida/.pyenv/versions/2.7.5/lib/python2.7/site-packages/socketIO_client/__init__.py", line 399, in _get_socketIO_session
    response = _get_response(requests.get, server_url, **kw)
  File "/home/hayashida/.pyenv/versions/2.7.5/lib/python2.7/site-packages/socketIO_client/transports.py", line 309, in _get_response
    response = request(*args, **kw)
  File "/home/hayashida/.pyenv/versions/2.7.5/lib/python2.7/site-packages/requests/api.py", line 55, in get
    return request('get', url, **kwargs)
  File "/home/hayashida/.pyenv/versions/2.7.5/lib/python2.7/site-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/hayashida/.pyenv/versions/2.7.5/lib/python2.7/site-packages/requests/sessions.py", line 383, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/hayashida/.pyenv/versions/2.7.5/lib/python2.7/site-packages/requests/sessions.py", line 506, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/home/hayashida/.pyenv/versions/2.7.5/lib/python2.7/site-packages/requests/sessions.py", line 168, in resolve_redirects
    allow_redirects=False,
  File "/home/hayashida/.pyenv/versions/2.7.5/lib/python2.7/site-packages/requests/sessions.py", line 486, in send
    r = adapter.send(request, **kwargs)
  File "/home/hayashida/.pyenv/versions/2.7.5/lib/python2.7/site-packages/requests/adapters.py", line 309, in send
    conn = self.get_connection(request.url, proxies)
  File "/home/hayashida/.pyenv/versions/2.7.5/lib/python2.7/site-packages/requests/adapters.py", line 217, in get_connection
    conn = self.proxy_manager[proxy].connection_from_url(url)
  File "/home/hayashida/.pyenv/versions/2.7.5/lib/python2.7/site-packages/requests/packages/urllib3/poolmanager.py", line 132, in connection_from_url
    u = parse_url(url)
  File "/home/hayashida/.pyenv/versions/2.7.5/lib/python2.7/site-packages/requests/packages/urllib3/util.py", line 397, in parse_url
    raise LocationParseError("Failed to parse: %s" % url)
requests.packages.urllib3.exceptions.LocationParseError: Failed to parse: Failed to parse: 2001:cf8:1:521:0:dddd:37fb:896c
Exception AttributeError: "'SocketIO' object has no attribute '_SocketIO__transport'" in <bound method SocketIO.__del__ of <socketIO_client.SocketIO object at 0x88ace2c>> ignored
```

**Comment by invisibleroads** [comment] 2015-01-09 10:24
We'll have something here soon.

**Comment by pjz** [comment] 2015-02-09 20:34
:+1: waiting for a fix for this too

**Comment by invisibleroads** [comment] 2015-02-15 16:48
Duplicate of #52

**Closed by invisibleroads** 2015-02-15 16:48 UTC
